import { defineConfig } from '@hey-api/openapi-ts';

// @hey-api/openapi-ts generates the typed REST SDK, response/error types, and
// zod schemas the dashboard uses, from the supervisor's committed OpenAPI 3.1
// spec (internal/api/openapi.json, itself generated by cmd/genspec from the
// Huma handlers). Every API call, error branch, and SSE event the SPA makes
// flows through this generated code, so it must stay in lock-step with the
// spec — regenerate with `npm run generate:client` after any spec change.
//
// Output lands in the `shared` workspace so both `frontend` and `shared`
// import a single typed client. See engdocs/architecture/api-control-plane.md
// for the tooling rationale.
export default defineConfig({
  input: '../../openapi.json',
  output: {
    path: 'shared/src/generated/gc-supervisor-client',
    postProcess: ['prettier'],
    importFileExtension: '.js',
  },
  plugins: [
    // bundle: false — import the fetch client from the `@hey-api/client-fetch`
    // dependency the `shared` workspace already declares, rather than bundling
    // a copy into client/ + core/ dirs. Keeps the generated output flat.
    { name: '@hey-api/client-fetch', bundle: false },
    '@hey-api/typescript',
    '@hey-api/sdk',
    'zod',
  ],
});
